export const MODEL_PATHS = [
	"assets/models/floor.glb",
	"assets/models/wall.glb",
	"assets/models/character-human.glb",
	"assets/models/coin.glb",
	"assets/models/trap.glb",
	"assets/models/stairs.glb",
	"assets/models/chest.glb",
	"assets/models/barrel.glb",
	"assets/models/character-orc.glb",
	"assets/models/weapon-sword.glb",
];

export const AUDIO_PATHS = [
	"assets/audio/footstep00.ogg",
	"assets/audio/footstep01.ogg",
	"assets/audio/footstep02.ogg",
	"assets/audio/footstep03.ogg",
	"assets/audio/footstep04.ogg",
	"assets/audio/footstep05.ogg",
	"assets/audio/footstep06.ogg",
	"assets/audio/footstep07.ogg",
	"assets/audio/footstep08.ogg",
	"assets/audio/footstep09.ogg",
	"assets/audio/drawKnife1.ogg",
	"assets/audio/drawKnife2.ogg",
	"assets/audio/drawKnife3.ogg",
	"assets/audio/knifeSlice.ogg",
	"assets/audio/knifeSlice2.ogg",
	"assets/audio/chop.ogg",
	"assets/audio/metalPot1.ogg",
	"assets/audio/metalPot2.ogg",
	"assets/audio/handleCoins.ogg",
	"assets/audio/handleCoins2.ogg",
	"assets/audio/doorOpen_1.ogg",
	"assets/audio/doorOpen_2.ogg",
	"assets/audio/metalClick.ogg",
];
